### ISSUE TITLE
Translation into Russian and errors with Russian.

### ISSUE THREAD

**Issue by ZelefRU** [BrilliantTeam/ShulkerBoxPreview#1]
I translated the configuration file into Russian for my convenience and for the convenience of other Russian-speaking people.

I also want to draw attention to the fact that this link does not work` lang_lib: https://raw.githubusercontent.com/YTiceice/LangLib/main/lang`
Error 404,

+ problems when displaying Russian names in the continuation. There are no such problems with English.

If you have any questions, you can contact me on discord if I don't answer here Zelef#1628

=====================================================================

为了方便我和其他说俄语的人，我将配置文件翻译成俄语。

我还想提请注意这个链接不起作用 `lang_lib：https://raw.githubusercontent.com/YTiceice/LangLib/main/lang`
错误404，

+ 在后续中显示俄语名称时出现问题。 英语就没有这样的问题。

如果您有任何问题，如果我没有在这里回答，您可以通过 discord 联系我 Zelef#1628

![Screenshot_41](https://user-images.githubusercontent.com/95104322/211371351-ae21f678-6a02-42b3-837c-a705ddd8cdea.png)
![Screenshot_42](https://user-images.githubusercontent.com/95104322/211371358-f2393a2f-fa51-46aa-a5e6-be6704850333.png)
![Screenshot_43](https://user-images.githubusercontent.com/95104322/211371361-fe290e6a-d2f7-4241-aa20-eb9161c09951.png)
![Screenshot_44](https://user-images.githubusercontent.com/95104322/211371363-72b5a74e-961b-4c54-a856-1ee06a75787f.png)

**Comment by Koyorice** [comment]
go to another issue #2
